#!/usr/bin/env sh
set -eu

if git status --short | grep --quiet '^MM'; then
	printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
	exit 1
fi

bunx biome check --write --staged --files-ignore-unknown=true --no-errors-on-unmatched

bun run actions:build
git add .github/actions/*/dist

git update-index --again

bun run --workspaces typecheck
